server:
  port: 9999
#配置数据库
spring:
  datasource:
    jdbc.drive: com.mysql.cj.jdbc.Driver
    username: zql
    password: qaz123456
    url: jdbc:mysql://47.101.207.245:3306/wxarticle?characterEncoding=utf-8&serverTimezone=UTC&useSSL=false
#    username: root
#    password: qaz123456
#    url: jdbc:mysql://localhost:3306/wxarticle?characterEncoding=utf-8&serverTimezone=UTC&useSSL=false
  jpa:
      show-sql: true
#  #redis配置
#  redis:
#    host: 47.101.207.245
#    port: 6379
#    timeout: 60s
#    jedis:
#      pool:
#         # 最大空闲连接数
#        max-idle: 8
#        # 最小空闲连接数
#        min-idle: 0
#        # 等待可用连接的最大时间，负数为不限制
#        max-wait: -1s
#        # 最大活跃连接数，负数为不限制
#        max-active: -1

#发送邮件的配置
  mail:
    host: smtp.qq.com
    username: 2672575920@qq.com
    #授权码，不是密码，从邮箱方面找
    password: apnhbmpzqxaxebbd
    properties:
      mail:
        stmp:
          enable: true
        starttls:
          enable: true
          required: true
  #freemarker配置
  freemarker:
    template-loader-path: classpath:/templates/
    suffix: .ftl
    cache: false
    charset: utf-8
    request-context-attribute: request

#activemq配置,这里配置一定不要有空格，否则会出现jsTemplate无法注入的报错
  activemq:
    broker-url: tcp://127.0.0.1:61616
    # 默认代理URL是否应该在内存中。如果指定了显式代理，则忽略此值。
    in-memory: true
    pool:
      enabled: false
    user: admin
    password: admin
  #默认情况下activemq提供的是queue模式，若要使用topic模式需要配置下面配置
  jms:
    pub-sub-domain: false

#公众号相关配置
public:
  #java团长,java技术栈,马龙翻身,纯洁的微笑,菜鸟架构,python之禅,一只鱼的传说
  account: javatuanzhang,javastack,coderising,keeppuresmile,hi-arch,VTtalk,lidayushu
  #搜狗微信的基础地址
  baseUrl: http://weixin.sogou.com/weixin?type=1&ie=utf8&query=
  #文章地址的地址头,用于拼接，并不需要后台做https请求
  urlHead: https://mp.weixin.qq.com
#邮件内容的相关配置
mail:
  from: 2672575920@qq.com
  to: 2672575920@qq.com
  subject: 今日更新文章
#定时任务的相关配置
quartz:
  #需要定时调度的方法
  method1: execute
  #调度的时间和次数等corn表达式
  corn: 0 15 9 * * ?

#配置重新获取url的host地址
addr:
  host: http://localhost:9999



